name: Cypress Tests
on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Start backend server
        run: node . &
        working-directory: ./backend  # adjust path to your backend
        env:
          NODE_ENV: test
          PORT: 8080  # or your backend port

      - name: Start frontend server
        run: npm run dev &
        working-directory: ./frontend  # adjust path to your frontend
        env:
          NODE_ENV: test
          PORT: 3000  # or your frontend port

      - name: Wait for servers to be ready
        run: |
          timeout 60 bash -c 'while ! curl -s http://localhost:5000 >/dev/null; do sleep 1; done'
          timeout 60 bash -c 'while ! curl -s http://localhost:3000 >/dev/null; do sleep 1; done'
          echo "Both servers are up!"

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./frontend  # where your Cypress tests are
          config: baseUrl=http://localhost:3000
