name: Cypress Tests
on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Start Backend
        run: node . & # This starts your dev server in background
        working-directory: D:\LSTV\LSTV Repositories\REACT-POS-OTC-NEW\pos-otc-be  # adjust if your package.json is in a subdirectory

      - name: Start Frontend
        run: npm run dev &
        working-directory: D:\LSTV\LSTV Repositories\REACT-POS-OTC-NEW\pos-otc-fe
      
      - name: Wait for server to be ready
        uses: cypress-io/github-action@v5
        with:
          wait-on: 'http://localhost:5173/'  # waits for server to be ready
          wait-on-timeout: 60  # seconds

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: cypress/e2e/cristel_cypress.spec.cy.js  # where your Cypress tests are located
          config: baseUrl=http://localhost:5173
